### ISSUE TITLE
how to retrieve features

### ISSUE THREAD

**Issue by emdete** [jnohlgard/python-v4l2capture#10]
hi,

i wonder how i can get the features that a webcam supports. if i use my favourite webcam tool guvcview it shows possible resolution and fps settings. did i miss something or does guvcview use a different api for that or is it just not implemented for now?

regards, michael

**Comment by jnohlgard** [comment]
It is not implemented at the moment. You'll need to add some more methods to the Video device class. I don't have any time to work on this project, but you can look at http://git.linuxtv.org/cgit.cgi/v4l-utils.git/tree/utils/v4l2-ctl for some example code for enumerating all available formats. Open a pull request if you implement it and I can merge it into master.
